### ISSUE TITLE
[Feature Request] Custom Deadzones

### ISSUE THREAD

**Issue by Ales724** [Mr-Wiseguy/Zelda64Recomp#110]
Please add an option for custom deadzones for analog sticks, i think it's too sensitive

**Comment by Ammako** [comment]
This is a planned feature

**Comment by GabrielCNoble** [comment]
I managed to hack in a deadzone slider. It seems to work fine so far.

![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/16003370/7e01b80c-7dc9-448c-80bb-d5ba67309ddd)

It took a little while but eventually I figured out where I had to change things to make it work. I kinda wish you guys had used something closer to an immediate mode ui for this. It'd make this sort of modification a ton easier, and the ui code would probably be significantly smaller than what it currently is.

**Comment by Mr-Wiseguy** [comment]
Thanks for taking a look. Will you be opening a pull request with that implementation?

As for why we didn't use an immediate mode UI, while they can be easier to work with they almost always result in a much worse user experience and don't look nearly as good. Because this project uses RmlUi, we're able to provide a clean looking UI with full keyboard and controller navigation while also being able to quickly iterate on the styling of the entire interface with hot reloading.

**Comment by GabrielCNoble** [comment]
Wasn't planing to but I can do it. How should I go about doing it?

Also, I was mainly thinking of Dear ImGui when I mentioned the UI part. It's widely used in the gamedev industry for things like tooling.

**Comment by Mr-Wiseguy** [comment]
You can just open the PR with the changes you've made. If you aren't interested that's fine too.

> Also, I was mainly thinking of Dear ImGui when I mentioned the UI part. It's widely used in the gamedev industry for things like tooling.

I'm familiar with ImGui, and the project does use it for the internal renderer debug menu. It is not suitable for an end-user interface for the reasons I mentioned and some others (no controller/keyboard support, not nearly polished enough for a user interface targeted at end users, not enough options for styling, no support for right-to-left text or advanced text shaping, etc.). Most immediate mode UI toolkits suffer from these problems because they set out to solve a different problem than what you'd use for a normal user interface, and we investigated many toolkits before settling on what we used.

**Comment by Mr-Wiseguy** [comment]
Closed as this was added in 1.1.0.
