### ISSUE TITLE
[Question] Building for lighweight, non-desktop GNU/Linux systems

### ISSUE THREAD

**Issue by vanfanel** [Mr-Wiseguy/Zelda64Recomp#134]
Hi there,

I'm going to try and build this on my lightweight GNU/Linux system, where I use KMS/DRM and a light Wayland compositor for graphics. It doesn't have any X11 libs anymore, as these are not needed for modern graphics on small GNU/Linux systems.

Looking at the CMake files, I found that X11 is searched for here:

https://github.com/Mr-Wiseguy/Zelda64Recomp/blob/89af45ae343ff81c844603d1f8b0b608373f4719/CMakeLists.txt#L227

As you know, SDL2 already takes care of rendering context creation and management, so there's zero need for X11 when using SDL2: you use SDL2 for context initialization (that includes Vulkan rendering context) and SDL2 uses Wayland, X11, KMS/DRM or whatever under the hood.

So, how's legacy X11 needed? Could it be removed in favor of abstract SDL2 context management?

Thanks!

**Comment by vanfanel** [comment]
Hmm.. nativefiledialog-extended is also looking for libGTK3 here:

https://github.com/btzy/nativefiledialog-extended/blob/17b6e8ce219c0677f94b63636abb9296b28841ca/src/CMakeLists.txt#L18

Thank makes it impossible to have this on non-desktop systems, like GNU/Linux handhelds, etc

Would it be possible to make nativefiledialog-extended an optional dependency and passing the filename as a parameter directly instead of depending on it if it's disabled at buildtime?

**Comment by Mr-Wiseguy** [comment]
Vulkan surface creation via SDL2 was merged into the modding branch, which adds support for other environments like Wayland and KMS/DRM. However, x11 is still required for building because we have to support x11 environments. I could maybe consider a PR to allow building without x11 support, but I'd be hesitant to merge it since I have no pure wayland environment to test that and it's not something I'll be working on myself.
