### ISSUE TITLE
[Question] How do I convert savefiles from emulators to use them in Recomp?

### ISSUE THREAD

**Issue by SpicyWheatPeppers** [Mr-Wiseguy/Zelda64Recomp#143]
Does anyone know the windows directory and how to get an emulated save into the port?

**Comment by SpicyWheatPeppers** [comment]
Found it C:\Users\USERNAME\AppData\Local\Zelda64Recompiled\saves

but how do you convert it

**Comment by Reonu** [comment]
Hello, thanks for the question! In the future, please give your issue a proper name that summarizes the issue you're having.

In order to convert a PJ64 savefile, you have to byteswap it. On Linux, you can do it with the following command:
`objcopy -I binary -O binary --reverse-bytes=4 path/to/file`

I don't know how to do it on Windows from the top of my head. If you figure it out feel free to share it here.

**Comment by SpicyWheatPeppers** [comment]
Thank you!! I did figure it out here's a website https://savefileconverter.com/#/flash-carts

and I WILL BUTCHER THIS if I don't just show you.

**Comment by SpicyWheatPeppers** [comment]
https://youtu.be/JayEAp_zW3E

**Comment by Nantris** [comment]
Anybody know how to do this with Mupen's SRM files it uses for saves?

Thanks very much for the video @SpicyWheatPeppers! Unfortunately YouTube only shows it at 720p and I can't really read the filenames, but I can see there's no SRM for Project64 :(
