### ISSUE TITLE
[Feature Request] Discord / Community chat

### ISSUE THREAD

**Issue by SealEnthusiast** [Mr-Wiseguy/Zelda64Recomp#162]
I think it would be nice to have a community chat for discussion and help with the project, Discord and other applications element would do very nicely

**Comment by ActuallyTheOwner** [comment]
I would prefer that
I found a bug with the laundry pool
If you interrupt the bell with the song of time as deku link, then the save file gets corrupted and will not load.
I do not know where to find another savefile that would work with the port

**Comment by SealEnthusiast** [comment]
What are you talking about?

**Comment by Seal-Enthusiast** [comment]
I'm sorry what are you talking about?

**Comment by ActuallyTheOwner** [comment]
Sorry for the late response, there is a bug with using Deku link in the laundry pool.
To reproduce, simply use the Deku bubble on the bell in the laundry pool.
As the bubble is bouncing off the bell, and before the cutscene, play the song of time. 
Doing this will corrupt the save file. 

A discord to report bugs would help

**Comment by ActuallyTheOwner** [comment]
A discord would also help people communicate bugs better
No idea how I did it, but I lost my sword somehow after transforming from Goron to Zora, then to Link in Ikana Graveyard 
Edit: it was not the hex you can get from spirits, the sword is just not there

**Comment by Mr-Wiseguy** [comment]
> I think it would be nice to have a community chat for discussion and help with the projectDiscord and other applications element would do very nicely

Unfortunately I don't have the resources to run a Discord in terms of moderating it, so I probably won't be making an official one for the project any time soon. I'm also not willing to take the risk of letting people I've never met before moderate a server I own, sorry.

@ActuallyTheOwner Issue reports would stay on GitHub even if there was a discord, since GitHub is designed for that sort of thing. Please make a new issue and add details to the problem if you have something to report instead of commenting on an existing unrelated issue.
