### ISSUE TITLE
[Request] Support for actual 4:3 aspect ratio on 4:3 monitors

### ISSUE THREAD

**Issue by Moshugan** [Mr-Wiseguy/Zelda64Recomp#165]
I know that the appeal of a port like this is that you can play the game on a modern system with widescreen and high resolutions, but it would be great if there was actual 4:3 aspect ratio support in the game for authenticity. As it is now, the "original" aspect ratio option in the game is a fake 4:3 view rendered in a 16:9 window, making it unsuitable for physical 4:3 monitors.

**Describe the bug**
When I try to use the "original" aspect ratio on a 4:3 monitor, the game is rendered as a tiny box in the middle of the screen, with black bars all around.

**To Reproduce**
1. Hook up your device to a 4:3 monitor.
2. Start the game.
3. Game starts in 16:9 aspect ratio with black bars on top and bottom.
4. Go to "Graphics" settings and change the aspect ratio to "Original".
5. The game is still rendered at 16:9 with black bars on top and bottom, but the game view is reduced to 4:3, making it appear in the middle of the screen with black on all sides of the screen.

**Expected behavior**
I expected "Original" aspect ratio to fill the 4:3 monitor with a 4:3 view of the game. I expected the game to render the view at 4:3 instead of 16:9.

**Screenshots**
![kuva](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/58215105/6c709df0-74d8-4683-b628-ba23d61cde58)

**Desktop (please complete the following information):**
 - OS: SteamOS
 - Version: v1.0.0
 - CPU: Steam Deck LCD version
 - GPU: Steam Deck LCD version

**Comment by Reonu** [comment]
Recomp already supports any aspect ratio, including 4:3. And by this I mean real 4:3, yes, not pillarboxed. This is an issue with your setup. You can see the FPS counter on the top-left corner. This would be literally impossible if your output and rendering resolutions were correctly configured. 

First, make sure you manually select a 4:3 resolution in the Steam Deck's display settings. For example, let's say 640x480.

Secondly, go to the properties of the game on your Steam library and scroll down to "Game Resolution". Set the same 4:3 resolution from before there.

I'm closing the issue since this feature already exists, but feel free to respond to the issue anyways if you're still having trouble configuring your setup properly.

**Comment by Moshugan** [comment]
> Recomp already supports any aspect ratio, including 4:3. 
> First, make sure you manually select a 4:3 resolution in the Steam Deck's display settings. For example, let's say 640x480.
> Secondly, go to the properties of the game on your Steam library and scroll down to "Game Resolution". Set the same 4:3 resolution from before there.

I did have a correct 4:3 resolution set in Steam system settings, but it wasn't enough. But setting the same resolution into the game properties did the trick! Inside the game it also needs to be set in Fullscreen mode for it to work. If it's in Windowed mode it will still try to display in 16:9 letterbox. Thank you so much!
