### ISSUE TITLE
[Feature Request] More texture filtering methods

### ISSUE THREAD

**Issue by glitchedman** [Mr-Wiseguy/Zelda64Recomp#171]
Feature request:
Please consider adding more texture filtering methods: bilinear, nearest-neighbor, maybe anisotropic too?

**Comment by glitchedman** [comment]
Of course, I mean being able to change them from options menu.

**Comment by Reonu** [comment]
Bilinear and nearest neighbor filtering is outside of the scope of the project, which aims to render graphics accurately and only provide enhancements on top of it and not subjective changes such as making the textures point-filtered or "PSX-style".

RT64 renders textures with the filtering that the game requests. Textures that are already point filtered in the game are point filtered in Recomp / RT64. Doing otherwise would change the game's artstyle. It's a subjective change that is better suited for a mod when mod support releases.

As for anisotropic, it will be automatically enabled for HD textures when support for that comes. For the vanilla textures, it's arguably not useful unless mipmap generation is added. This might come in the future but it's not a priority.

**Comment by SirYodaJedi** [comment]
4-point bilinear filtering is already possible from the debug menu by disabling 3-point filtering. This isn't a persistent setting however (despite what the menu label implies), so it has to be configured from the F1 menu each time the game starts up.

I'd say the option should be exposed (or at least available as a hidden config file edit), as people who grew up playing the game on the GameCube or Virtual Console would be accustomed to the less blurry look that 4-point bilinear filtering offers (remember, the Wii and Wii U are retro already).
