### ISSUE TITLE
Application doesn't show up in game mode on Steam Deck

### ISSUE THREAD

**Issue by crisinho** [Mr-Wiseguy/Zelda64Recomp#184]
So, I feel like this isn't necessarily an issue with this awesome project but I've run into an issue where I can't see this game in the game mode on my Steam Deck. 

I followed the instructions (extracted linux version to the /deck/home/Downloads directory, added the program to steam as a non steam game) and it shows up as long as I'm in desktop mode. It also launches absolutely fine in desktop mode, I can select the rom and start the game. However, as soon as I change to game mode it's like I never added it to Steam in the first place. I should also add that other programs that I add as a non steam game do show up normally, such as Firerfox or other Flatpaks.

I already tried extracting it to different folders such as the Desktop folder or a different one on my SD card but to no avail. I also tried to force the "Steam Linux Runtime" as compatability which also didn't work. At last I tried to rename the application to include .application or .AppImage - still no luck.

I found someone who had the same problem in a youtube comment who had the same problem but he could solve it by extracting it to the downloads folder (which I tried but didn't work for me). 

I'm not the most knowledgable person when it comes to linux but usually I can find myself around a problem but this time I'm out of ideas. Maybe someone on here has some kind of tip how to make it work.

Thanks for your great work on this project though!

**Comment by Shivaan88k** [comment]
Was having this same issue, and it may not permanently fix it, but hopefully the dummy at Valve who caused it will fix it before too long. Finally found a fix.
In desktop mode, exit steam, then go to /home/deck/.local/share/Steam/userdata/userID/config (userdata will be a series of numbers, your steam friends identifier) and backup shortcuts.vdf, then go to ...userdata/0/config, and backup that shortcuts file as well. Backing up isn't totally necessary, but be safe. Then what I did is copied the userdata .vdf to the 0 location (I did this because I've got a crap load of non steam stuff that wasn't showing up in desktop mode). Then open Steam again and add Zelda64 as normal, and also any other games that have had this issue, and make any changes you want before going back to gaming mode. Once done, copy the .vdf from the 0/config folder to the userID/config folder. 
If all went well, you should be good to go, if not, be glad you made backups.
I wish I could say I thought of this but I got the answer from here https://steamcommunity.com/app/1675200/discussions/1/4357873276732975202/ on a post by nad on page 2.
Good luck!

**Comment by Lucaspec72** [comment]
Not convinced this is a Zelda64 Recomp related issue, sounds like it would be a general steam deck issue ? never had this issue myself, but i don't see how this could be the recomp's fault, as any issue caused by it would be after starting it. It not even showing up in gamescope is likely a issue with gamescope or the steam client.

**Comment by Shivaan88k** [comment]
Yeah it's a Steam client issue.

**Comment by Shivaan88k** [comment]
Yeah it's a Steam client issue, from a recent update. Funny part is, it's even messing up the stable updates.

**Comment by crisinho** [comment]
@Shivaan88k Thanks a lot for your input and the link to the Steam Forum discussion. I already thought that it might be Steam related but I didn't stumble over the discussion on Steam. Even better if it's not Zelda64 Recomps issue.

I guess Valve will address this issue in the coming days - they usually fix these pesky things quite fast. 
Anyway, thanks for the help, I think I will just wait it out.
