### ISSUE TITLE
[Feature Request] Forced 16:9 aspect ratio for using Steam Deck docked (currently displays as 16:10 on TV)

### ISSUE THREAD

**Issue by Bluejinjo** [Mr-Wiseguy/Zelda64Recomp#225]
When docking a Steam Deck and playing through a 16:9 display, the game is still displayed in 16:10, since that's the SD's game window. An option to force 16:9 or any aspect ratio outside of the Steam Deck's display window of 16:10, would be great.

I'm not sure if there would be a way for this to be automatically detected, but if so, an auto feature would be convenient.

**Comment by Reonu** [comment]
Hello!

Well, it's a 16:10 window because you have it set that way in SteamOS. SteamOS is currently reporting that the native screen resolution is 1280x800. Recomp can't do anything about that, it's dealing with the resolution that SteamOS claims your display has, so you have to change your settings in SteamOS.

First of all, if you haven't already, go to the Display settings in your Steam Deck and manually set your desired resolution for your external display.

Secondly, and this is the important part, go to the properties of Zelda 64 Recompiled in your Steam library. Then, scroll down until you see "Game Resolution". Set it to "Native", or manually set it to the resolution you want (1280x720, 1920x1080, whatever). If you set it to something other than "native", make sure to not check the "set resolution for internal and external display" toggle, since that would make it render at this resolution even in handheld mode, which you probably don't want.

After changing the resolution there, the game will run at the correct resolution for your TV, as long as you boot it up while the Deck is already connected to the TV.

Hope this helps. Closing since this is not an issue with the project.

**Comment by Bluejinjo** [comment]
> Hello!
> 
> Well, it's a 16:10 window because you have it set that way in SteamOS. SteamOS is currently reporting that the native screen resolution is 1280x800. Recomp can't do anything about that, it's dealing with the resolution that SteamOS claims your display has, so you have to change your settings in SteamOS.
> 
> First of all, if you haven't already, go to the Display settings in your Steam Deck and manually set your desired resolution for your external display.
> 
> Secondly, and this is the important part, go to the properties of Zelda 64 Recompiled in your Steam library. Then, scroll down until you see "Game Resolution". Set it to "Native", or manually set it to the resolution you want (1280x720, 1920x1080, whatever). If you set it to something other than "native", make sure to not check the "set resolution for internal and external display" toggle, since that would make it render at this resolution even in handheld mode, which you probably don't want.
> 
> After changing the resolution there, the game will run at the correct resolution for your TV, as long as you boot it up while the Deck is already connected to the TV.
> 
> Hope this helps. Closing since this is not an issue with the project.

Amazing! Thanks very much for that, I've only had my Deck in the last year and I'm still finding more things out about it. Setting the resolution fixed it for me.

Apologies for taking your time up raising it as an issue on here. I assumed because SoH worked fine on the TV it may have been an issue with the MM recomp, but that must already be set to behave with the native resolution setting.

Thank you :)
