### ISSUE TITLE
Steam Deck - performance and battery drain

### ISSUE THREAD

**Issue by BeardedJellyfish** [Mr-Wiseguy/Zelda64Recomp#244]
**Describe the bug**
When playing the opening deku scrub section I would get 90fps and 6+ hours on a fully charged Steam deck OLED. Now it can’t hit above 80fps and the battery lasts 2.5 hours on a full charge. 

Originally changing to 60fps would fix performance and battery drain issues. But now setting to 60fps causes dips to 30s and 2 hour battery. 

**To Reproduce**
1. Go to settings and change frame rate to either display match or manually to 60 or 90. 
2. Once game gets past file loading it chugs. 

**Expected behavior**
Like before it should run at full 90fps upscaled with at least 6 hours on a full charge. 

**Desktop 
 - running Steam Deck OLED 
Beta branch OS 3.5.19 build 20240422.1 
Kernel version 61.52-valve16-1-Neptune-61

**Additional context**
I turned off auto save that’s the only other thing I changed

**Comment by Reonu** [comment]
Hi, thanks for the report.

Many people, myself included, have run the game on both versions of the Steam Deck with excellent battery life and performance.

Are you using 2x resolution in combination with 4x downsampling by any chance? That would destroy performance since it would render internally at 4k. Or have you changed the resolution settings in the game properties on Steam to something higher than the Deck's native screen resolution?

I've also noticed you're using a SteamOS beta. Does the same thing happen if you leave the beta?

**Comment by BeardedJellyfish** [comment]
Hello,

At this time I've tried every combination of graphics settings I can think of. I also changed back to the stable OS branch. While keeping refresh rate set to match the display I've done the following and gotten the responses
- changed resolution to original 240p with no AA or downsampling would seem to keep a more stable 90FPS but the battery life went down to 3.5 hours
- changed to 2x resolution with no AA or downsampling got me closer to 80s FPS with the same 3 ish hours of battery life
- adjusted the resolution in steam to 1200x800 and set resolution setting to match the display with no sampling or AA and was getting 60 to 80 fps with less than 3 hour battery
- changed to 60 fps in the settings while changing the resolutions to 240, 480 and matching the display and got on average an extra 35 minutes estimated battery time.
I've also verified there are no TDP limits in place and re downloaded the newest build after completely clearing the old one. The only thing I haven't tried at this point is to make a new dump of my rom.

EDIT NOTE - I'm noticing that the CPU is draining the most power. Drawing around 6 or 7 watts while I remember it being lower when I wasn't having issues.

**Comment by BeardedJellyfish** [comment]
I just tried clearing the zelda64recomp folder from .config and started a new save. At first it was chugging and draining the battery before evening out. Then when I got to clock town it would keep a stable 90fps but the cpu usage would randomly fluctuate to just over 1 watt to 8 watts while drain the battery before evening out and then back again. I'm about to try the windows build with a proton layer. 

Edit - windows build with proton seems to behave the exact same way

**Comment by Mr-Wiseguy** [comment]
Those spikes sound like the driver optimizing shaders in the background so that the game can run better. In a normal play session, that should basically go away after a few minutes of normal gameplay. This project chooses to not save the optimized shaders to avoid using a lot of drive space and to avoid issues when the shaders get updated between versions. I wouldn't put too much faith in the reported battery usage unless you've been playing for more than 5 or 10 minutes.

**Comment by BeardedJellyfish** [comment]
I believe I fixed it. I cleared the Zelda recompile folder from .config and it seems to work now. Solid 90fps with minimal dips and cpu spikes for shader compilation vs the uneven frame rate with consistently high cpu usage. I'm wondering if a graphics setting didn't properly turn off when I set it to in the launcher.

**Comment by RhanCandia** [comment]
I'm sorry to be reviving an old ticket but may I ask @BeardedJellyfish how that power consumption is now?
I tried it and I was hitting nearly 15w with all the default configurations.

**Comment by BeardedJellyfish** [comment]
@RhanCandia it seems to be working now. What ended up fixing it was I had to delete the main recomp folder that holds your save file. Once I did that it started working. I think some of the graphics settings didn't get switched off like they're supposed to when certain settings are on or off like the downsampling. Try deleting that folder and leave the settings to whatever it automatically sets.
