### ISSUE TITLE
[Bug] Shimmering/Glitching Textures and Fog

### ISSUE THREAD

**Issue by SonicRay100** [Mr-Wiseguy/Zelda64Recomp#254]
**Description**
Some textures and fog shimmers/glitches.

**To Reproduce**
1. The texture for the hole in the wall in the Knife Chamber (the room that opens with the room key in the Stock Pot Inn) shimmers/glitches upon opening the door (entering and leaving). See screenshot.
2. While waiting for Kafei in the staff room off the Stock Pot Inn, the textures and fog on the wall where the door is will start shimmering/glitching as soon as he enters the room (this might happen when the player enters the room as well. 

**Screenshot**
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/69745689/9766e946-6970-40c9-b55c-4ecd40da590c)

**Desktop**
 - OS: Windows 10 Pro, 22H2
 - OS Build: 19045.3930
 - CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
 - GPU: MSI GTX 1080 Gaming X 8GB
 - RAM: 16 GB
 
**Additional Context**
It is difficult to see in a screenshot (easier to see when maximised) but you can see a sort of shimmer/glitching on the hole in the wall's texture. The texture goes back to normal once Link's animation is complete. I'm not sure If I've seen this at any other point while playing so these only two I know for certain. I am still playing so I will add more instances of this if I notice any.

Attempted to get screenshot of the staff room shimmer/glitch but the "Reuniting Kafei and Anju" quest is quite long and the debug warp doesn't have the staff room in the Stock Pot Inn as an option.

**Comment by Mr-Wiseguy** [comment]
Thanks for the report. This is an issue in the original game and not caused by this project. I've attached a video of it in angrylion RDP, but I've verified it happens on console as well. The Kafei fog issue is also present in the original game as well.

https://github.com/Zelda64Recomp/Zelda64Recomp/assets/68165316/bbf5d80f-8a6b-4fc1-93f3-e8c5d7b9f528

And here's a link to footage of console capture of the Kafei fog issue:

https://youtu.be/iNjX7UzRQyU?t=56632

Fixing vanilla issues is outside of the scope of this project, but this would be well suited to a mod (once modding support is added).

**Comment by SonicRay100** [comment]
Really? I never noticed that before, then again I did play the PAL version when I was a kid and my memory may be fuzzy if it was present. Cool no worries then :). Regardless, a staff room warp would be nice for the next version for testing purposes.
