### ISSUE TITLE
Portable option

### ISSUE THREAD

**Issue by Flax4** [Mr-Wiseguy/Zelda64Recomp#27]
Would it be possible let this have a "portable" option? As in everything related to this gets saved in the folder I have it in instead of having files being written to appdata/local?

**Comment by Mr-Wiseguy** [comment]
This is a pretty good idea, I'll consider it for a future version. Thanks for the suggestion!

**Comment by FoxbitDreamtail** [comment]
In a lot of emulators you can make the emulator completely portable by putting a empty it portable.txt file in the file system in the exact same directory as the executable, perhaps something like this system would be in order?

**Comment by grimson73** [comment]
I accidentally opened the same feature request, closed that one and chimed in on this one :)

**Comment by emeraldroguefan** [comment]
Portable mode is definitely essential I would say, lots of people these days sync their emulators with Dropbox and their portable PCs / Steam Decks

**Comment by FoxbitDreamtail** [comment]
It's also important if you ever want to say put the emulator on a removable storage device to take it in between machines so that you don't have to reset your save progress every single time you wanted to test out the game on another computer or if you wanted to go over to a friend's and play your game over at friends you wouldn't have to lug a computer with you, just take your removable USB flash disk, people forget that years ago we used to have memory cards which served a similar purpose except this would be the memory card for PCs and I'm all down for it.

**Comment by SonicRay100** [comment]
I honestly hate whenever an app places configs/saves in AppData and prefer it to be either in the executable's directory or somewhere in the documents directory.

I like having all my saves consolidated in the My Games directory since most games place configs/saves there. A way to satisfy everyone would be to allow users to define either an absolute or relative directory path for the configs/saves (maybe add a button that sets a relative directory path to make it easy).

**Comment by FoxbitDreamtail** [comment]
I still think that my idea would be better because your idea would mean that a config file would need to be left behind in order to show where is the absolute definition of where the files are, with my solution it's literally just put a file in and then everything will be written in the same directory, simple as that.

**Comment by SonicRay100** [comment]
That's true that a file would need to be in the main directory. Though not a big deal, perhaps a middle ground is have the My Games directory as the default option and portable.txt for portable users. Anything is better that AppData (or the registry for that matter).

**Comment by dcvz** [comment]
This was implemented in https://github.com/Zelda64Recomp/Zelda64Recomp/pull/368 and will be in the next release!
