### ISSUE TITLE
[Feature request] HUD buttons change

### ISSUE THREAD

**Issue by 111ebobo** [Mr-Wiseguy/Zelda64Recomp#292]
I want to suggest adding different textures for buttons to correspond your binds. For example: Replace C buttons with B Y RB (or whatever they was binded), A and B buttons with A(with green color) and X buttons for XBox controllers

**Comment by FSR-1** [comment]
Pretty sure this isn’t in the scope of project

**Comment by Mr-Wiseguy** [comment]
This is something that's been considered and I would like to have it in the base project, the issue mainly comes down to the fact that there are so many controllers out there with different button names and layouts so it would be difficult to implement. I'll close this for now but I don't expect we'll get to this for a while because of that.

**Comment by FSR-1** [comment]
Ok my bad I guess I was wrong

**Comment by 111ebobo** [comment]
> This is something that's been considered and I would like to have it in the base project, the issue mainly comes down to the fact that there are so many controllers out there with different button names and layouts so it would be difficult to implement. I'll close this for now but I don't expect we'll get to this for a while because of that.

I think that at least some presets like ps, Xbox, direct input ,and Nintendo controllers
