### ISSUE TITLE
[Feature Request] HDR Support

### ISSUE THREAD

**Issue by colltyp** [Mr-Wiseguy/Zelda64Recomp#294]
is probably something for the far future, but hdr in the game, perhaps also with this ray tracing feature, would have potential

**Comment by 111ebobo** [comment]
I think it will appear with RTX

**Comment by DagothUrTheFalse** [comment]
Worst case you might be able to use nvidias HDR feature for normally SDR games

**Comment by Mr-Wiseguy** [comment]
This would be a feature in RT64, but it's also just not doable while preserving remotely accurate visuals. Many graphical effects in N64 games rely on lighting and shading having exact bounds, and changing those bounds (which would be needed to have a higher range of colors for HDR) would break those effects.

If you're interested in some of the nitty gritty details, colors on the N64 wrap in the range of (-0.5, 1.5) during rendering and are then clamped to (0.0, 1.0) after applying the color wrap. This is used for many effects in this game in particular, such as the "curse" effect that Skull Kid does and fire arrows. HDR requires expanding the maximum color values above 1.0, and without changing the color wrap/clamp behavior there would be no actual difference when HDR was active. On the other hand, changing that behavior means all of the effects which were designed around the specific color thresholds would now break, so that's not an option either.

The ray traced renderer from RT64 that's coming in the future may be able to work around this issue since lighting is partially applied after the base N64 colors are rendered, but then the bigger issue is that neither Darío nor I actually have an HDR display to test with.

**Comment by colltyp** [comment]
> This would be a feature in RT64, but it's also just not doable while preserving remotely accurate visuals. Many graphical effects in N64 games rely on lighting and shading having exact bounds, and changing those bounds (which would be needed to have a higher range of colors for HDR) would break those effects.
> 
> If you're interested in some of the nitty gritty details, colors on the N64 wrap in the range of (-0.5, 1.5) during rendering and are then clamped to (0.0, 1.0) after applying the color wrap. This is used for many effects in this game in particular, such as the "curse" effect that Skull Kid does and fire arrows. HDR requires expanding the maximum color values above 1.0, and without changing the color wrap/clamp behavior there would be no actual difference when HDR was active. On the other hand, changing that behavior means all of the effects which were designed around the specific color thresholds would now break, so that's not an option either.
> 
> The ray traced renderer from RT64 that's coming in the future may be able to work around this issue since lighting is partially applied after the base N64 colors are rendered, but then the bigger issue is that neither Darío nor I actually have an HDR display to test with.

i would have one up to HDR 600 even but yes it was a suggestion for the far future and not in the near future
