### ISSUE TITLE
[Feature Request] Rollback motion blur changes introduced in V1.1.0. Or provide option to turn it off.

### ISSUE THREAD

**Issue by fighterguard** [Mr-Wiseguy/Zelda64Recomp#328]
The new motion blur effect added in V1.1.0 is a noisy, disgusting mess. Sure, the blur effect is more intense, and a lot closer to how it looks in the original game running at 20fps, but why is it so horribly noisy? I honestly prefer the old one, which at least retains the crisp image. The most appalling thing about it is that the noise is most noticeable on black backgrounds, where nothing changes from one frame to another. Those should be the crispier ones, right?

Below are examples of what I'm talking about:
V1.0
![vlcsnap-2024-05-31-00h56m56s487](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/5727579/82f050dd-607a-477a-af6c-8b8c2b7f7c3d)

v1.1.0
![vlcsnap-2024-05-31-00h57m32s244](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/5727579/1b1aa06d-2c29-45b4-8407-e4aa55bf8098)

**Comment by Reonu** [comment]
It's "horribly noise" because the N64 game does that, on purpose. It's an intentional effect added by the original developers. Not rendering the effect that the developers intentionally put in there in 1.0.0 was a bug that is now fixed.

I should probably clarify that making the motion blur stronger has nothing to do with this. It's not a "side effect" of that in any way. We fixed two separate issues: the motion blur getting weaker at higher framerates, and the original noise effect during motion blur being missing, in the same update. But they're not related. 

Some people might not be aware of this effect because some official releases like the GameCube or Wii ones lack this effect. Bad emulator plugins also lack it. But this is what the motion blur scenes in the game are meant to look like. The Nintendo Switch Online does implement the effect (in weaker fashion) if you're curious. 

You are right about one thing which is the black backgrounds. In order to be completely true to the original effect on real N64 hardware, the completely black pixels should not have noise. This is a hard problem to solve but Darío might come up with something in the future. He explains it with more detail [here](https://github.com/Zelda64Recomp/Zelda64Recomp/issues/305#issuecomment-2135238046).

Closing as this is not an issue with the project.

**Comment by fighterguard** [comment]
I understand that this is intended behavior. But could you guys at least consider the possibility of adding a toggle to choose between the old and new implementations? Some might prefer the more "accurate" version, while others (like me), prefer the old one without the noise.
Thank you for the amazing work!

**Comment by fighterguard** [comment]
BTW, I checked the NSO version on Nintendo Switch. Specifically on the OLED model, because this type of noise is particularly noticeable (and annoying) on OLED displays. It is indeed true that the sequence with the spinning mask has a lot of dithering noise all over the black parts, including the letterbox bars, but the Happy Mask Salesman sequence is completely noise-free.

**Comment by loinmin** [comment]
> I understand that this is intended behavior. But could you guys at least consider the possibility of adding a toggle to choose between the old and new implementations? Some might prefer the more "accurate" version, while others (like me), prefer the old one without the noise. Thank you for the amazing work!

I made a comment similar to this as well, I definitely prefer the bugged out non-intentional grain/noise to be broken than fixed as it looks much nicer for an LCD as we are no longer on CRT's so it's a more modern look, hopefully we get an option to re-enable the bug as I much preferred it as it seemed cleaner for today's standards, if the goal of this project is to get everything accurate with a side of tweaks (such as allowing analog camera), I hope this one becomes possible to re-enable in future updates for us weirdos who like bugs that made the games cutscenes crispier :)
