### ISSUE TITLE
[Feature Request] Nintendo Switch Pro controller buttons recognition as a Switch controller not an Xbox one

### ISSUE THREAD

**Issue by Paco8478** [Mr-Wiseguy/Zelda64Recomp#362]
I want to make a request so the pro controller´s **X, Y, A and B** buttons are recognized as such and not switched to Xbox controller, even with the remapping available, during the start menu of the recompiled project A is B and B is A meaning if I press A on my controller it would cancel or go back instead of accepting the changes I want to make in settings.

**Comment by Mr-Wiseguy** [comment]
This project's menu doesn't use controller button names for this reason, as there are far too many different controllers and button layouts to account for all of them. Everything is handled the same and uses button directions instead of names for consistency between controllers. This won't be changed, as going by button names instead would mean the default mappings would vary from controller to controller.

**Comment by 111ebobo** [comment]
> This project's menu doesn't use controller button names for this reason, as there are far too many different controllers and button layouts to account for all of them. Everything is handled the same and uses button directions instead of names for consistency between controllers. This won't be changed, as going by button names instead would mean the default mappings would vary from controller to controller.

Well, there's not so many controllers: Nintendo, PS, Xbox and direct input
