### ISSUE TITLE
[Feature Request] Using keyboard to write the name of a save

### ISSUE THREAD

**Issue by TitouanMiellet** [Mr-Wiseguy/Zelda64Recomp#376]
I know it might be a lot of work for something that happens only once in a playthrought so I'm keeping my hopes low but I think it could be a nice addition.

**Expected behavior**
Using keyboard to write the name. "Enter" would work as "END"

**Screenshots**
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/94743095/71e0296c-2c6a-4ad7-86ac-a8aaa6710ea3)

**Comment by Mr-Wiseguy** [comment]
I do think this would be a pretty cool feature, but it'd also be surprisingly complicated to make it work this way. You'd not only have to heavily modify this screen to allow keyboard inputs to type in letters, you'd also have to disable any keyboard input bindings while this screen is open to prevent double inputs from happening.

For example, if you typed W while this screen was open (with the default keyboard bindings), it'd both type a W and also move the cursor up. Beyond that, you also need to still allow the cursor to work normally from other sources of input like controllers, otherwise keyboard would become the only way to input a name.

For those reasons, and also because this only happens once per playthrough like you said, this isn't a planned feature.
