### ISSUE TITLE
quitting before starting the game leads to an exception in `ultramodern::join_saving_thread`

### ISSUE THREAD

**Issue by briaguya0** [Mr-Wiseguy/Zelda64Recomp#386]
**Describe the bug**

quitting before starting the game leads to an exception in `ultramodern::join_saving_thread`

**To Reproduce**

1. open the game to the launcher menu
2. quit

**Expected behavior**

the game exits gracefully

**Screenshots**

![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/70942617/4ab2a193-c9cf-486b-998c-31e14c0b36b4)

**Comment by Mr-Wiseguy** [comment]
Thanks for the report. This is something that was introduced in the refactor to use N64ModernRuntime (so thankfully isn't in any of the releases), I just haven't had time to sort it out yet. Should just be a matter of not calling join_saving_thread if the game hasn't started, or starting the saving thread when the program opens instead of when the game starts.

**Comment by briaguya0** [comment]
yeah, i figure it's a decently quick fix, just something i've noticed a couple times so i figured making an issue instead of forgetting about it until i run into it again made sense

**Comment by dcvz** [comment]
This was fixed in the runtime which was updated in #392
