### ISSUE TITLE
Door sound is cut early

### ISSUE THREAD

**Issue by niklakis** [Mr-Wiseguy/Zelda64Recomp#391]
Original hardware does not have this problem

No glitches

The door opening sound is cut early in recomp, whereas on original hardware it plays in full. Wii VC and NSO also cut it a bit early but not as much as recomp

1. Find a door
2. Open door

Expected behavior
The sound is played in full or at least up to the same point as the N64

Desktop:
 - OS: [Windows 11]
 - Version: [23H2]
 - CPU: [R5 5600]
 - GPU: [Radeon RX 6700XT]
 - GPU driver: [24.5.1]
 
Video recorded on version 1.1.1. Settings do not matter but I am showing what I used.

https://github.com/Zelda64Recomp/Zelda64Recomp/assets/5071672/7664cefc-2504-4b4e-ac12-86b642e8498a

**Comment by MelonSpeedruns** [comment]
Pretty sure that's just the game loading faster than on N64 and NSO and WiiVC, cutting the door sound even more, so it is accurate behavior that the N64 would do too if it could load that fast.

**Comment by niklakis** [comment]
> Pretty sure that's just the game loading faster than on N64 and NSO and WiiVC, cutting the door sound even more, so it is accurate behavior that the N64 would do too if it could load that fast.

Sure, but in version 1.1.0 the dawn of a new day screen was extended to account for faster load times to match console timings. Should this not be the case here as well? IMO original console timings should be respected rather than accurate behavior of a souped up n64.

**Comment by MelonSpeedruns** [comment]
It's a hard choice. On one side you get proper sounds and timing, but on the other you're making loading times longer, which is what a PC port is trying to avoid.

**Comment by niklakis** [comment]
I mean, MM's loading times were never a problem to begin with. It may not even be needed to revert to the original loading times for everything, just adjust the problem areas.

**Comment by Krutonium** [comment]
Could just make it an option; Accurate Timing to account for sound effects, or Enhanced Load Speed.

**Comment by Mr-Wiseguy** [comment]
As others have stated, this is a natural effect of the game loading faster. Many people have said that they love how quickly the game loads now, even if it wasn't necessarily a problem in the original version, so I'm not interested in artificially increasing load times for this.

> Sure, but in version 1.1.0 the dawn of a new day screen was extended to account for faster load times to match console timings.

This door case is different, since it's not like the developers purposefully made loading slow on purpose to play out the door sound for longer. The game only waits after opening a door because it _has to_, since it has to load the new scene. There would have been no way around it on the original hardware, meaning the door sound was just that long for the sake of filling in time while the load happened.

On the other hand, the dawn of a given day screen and the four giants cutscene did have a reason to make them take longer to match the original timings. The developers could have made the dawn screen shorter if they wanted to by starting the scene load earlier, meaning they deliberately chose it to be the length it was. Likewise the giants cutscene was deliberately designed around console slowdowns as the audio desyncs from the visuals if there are no slowdowns. There's also just the fact that the dawn screens and giants cutscene happen far less often than going through doors. Those are the reasons why I opted to patch those.

> Could just make it an option; Accurate Timing to account for sound effects, or Enhanced Load Speed.

One of my main goals for this project, if not my singularly most important goal, is to keep it very simple and easy to use, even for somebody who has never played the game before. If the project started getting options to change small things like this, the menus would get bloated very quickly with lots of other small options to the point where it'd be an intimidatingly long list.

The best solution in my eyes would probably be to allow the door sound to continue playing after the next scene loads. However, it's a pretty low priority item compared to other things I'm working on like the modding framework and Ocarina of Time support. That means I won't be able to get to it myself, so I'm closing this as wontfix. With that said, I'd accept a good quality PRs that makes the change I suggested if somebody were to open it.

**Comment by niklakis** [comment]
> Many people have said that they love how quickly the game loads now

I am not going to doubt the feedback but that honestly surprises me a lot. Never in a million years would I have thought that MM would be enhanced by shorter loading screens of all things. But if that's the feedback that you are getting then so be it.

> One of my main goals for this project, if not my singularly most important goal, is to keep it very simple and easy to use, even for somebody who has never played the game before. If the project started getting options to change small things like this, the menus would get bloated very quickly with lots of other small options to the point where it'd be an intimidatingly long list.

I am disappointed that accuracy to the original behavior is not a top priority but maybe that is just me. Had I the skill and knowledge to work on this I would but alas I can only hope that someone who can shares my concerns and works on this IMO issue.
