### ISSUE TITLE
[Feature request] Ability to skip Song of Soaring cutscene

### ISSUE THREAD

**Issue by Stalfelz** [Mr-Wiseguy/Zelda64Recomp#396]
Just like with putting on transformation masks and such, you can skip a good portion of the song of soaring animation after seeing it the first time. Can't seem to skip it however, must watch the whole sequence every time.

**Comment by Reonu** [comment]
This isn't the case, you can't skip it on N64. This is a mandela effect moment, I also believed that to be the case, but I checked and nope.

I did try to add this feature before Recomp launched anyways, as a bonus, but faced 2 issues:
- If you skip the cutscene too early, the game crashes. Easy fix, just don't allow skipping it too early.
- When skipping the cutscene, the wings stop rotating, but Link keeps rotating, which looks unacceptably stupid. No idea how to fix this one.

I might revisit this and make a PR if I figure out the second issue.

**Comment by Reonu** [comment]
I'm editing the title since this is a feature request for a new feature and not a bug report, as there's no bug here.

**Comment by MelonSpeedruns** [comment]
They're probably thinking of the 3D version. I just tried skipping on N64 with a 100% save file and I can't.

**Comment by Stalfelz** [comment]
> They're probably thinking of the 3D version. I just tried skipping on N64 with a 100% save file and I can't.

i just tried on my switch after reading that and i couldnt *flops*
stg i was able to before, maybe on the gamecube or wii versions, but im probably just losing my mind
thought the song of time sequence was skippable too, and now im wondering if i imagined that as well >~<

**Comment by Krutonium** [comment]
> > They're probably thinking of the 3D version. I just tried skipping on N64 with a 100% save file and I can't.
> 
> i just tried on my switch after reading that and i couldnt _flops_ stg i was able to before, maybe on the gamecube or wii versions, but im probably just losing my mind thought the song of time sequence was skippable too, and now im wondering if i imagined that as well >~<

The GameCube and Wii versions are just Emulations of the originals with little to no changes; I don't think they even changed the button colors. (This isn't quite true for OoT though, where the Gamecube version did actually update the button colors for the GameCube controller)

The Song of Soaring/Song of Time animations have never been skippable to the best of my knowledge, except maybe in the 3DS version? I honestly never tried on the 3DS since I assumed you couldn't.

**Comment by Stalfelz** [comment]
> The GameCube and Wii versions are just Emulations of the originals with little to no changes; I don't think they even changed the button colors. (This isn't quite true for OoT though, where the Gamecube version did actually update the button colors for the GameCube controller)

The gamecube and wii releases did change the start, a and b button colors to reflect the gamecube controller as opposed to the n64 controller, but i believe that was the only change made. The switch release is the first time we got the original n64 button colors back iirc. It's also the first time majoras mask didnt have the audio glitch/hickup when walking between sections of clock town since the original n64 copy.

**Comment by aroenai** [comment]
> > The GameCube and Wii versions are just Emulations of the originals with little to no changes; I don't think they even changed the button colors. (This isn't quite true for OoT though, where the Gamecube version did actually update the button colors for the GameCube controller)
> 
> The gamecube and wii releases did change the start, a and b button colors to reflect the gamecube controller as opposed to the n64 controller, but i believe that was the only change made. The switch release is the first time we got the original n64 button colors back iirc. It's also the first time majoras mask didnt have the audio glitch/hickup when walking between sections of clock town since the original n64 copy.

GameCube had a number of changes, it was essentially a mash up of JP 1.1, PAL, and USA (in that order, with the differences being mostly cosmetic and audio related). One main difference was a reversion to the Zora Link boomerang animation that mode the pots mini game easier and matched the original mechanics from Japanese (Link takes a step back, so 3 backflips are perfectly aligned. USA removed the back step so there was manual alignment to do). To work around a number of limitations in their emulator they hard coded many checks to correspond with invalid writes to 0x81000000 in ram for saving to the memory card and stream audio (ex. The ending credits theme and the chime when correctly playing a song on the ocarina which means they are silent when playing the rom on N64 emulators). Wii was interesting since they replaced textures at run time - smaller flames, smaller Deku bubble projectiles, darker stray fairies, changing the shield color on the Death Armos, and making Goron Link's skin darker are notable examples.

**Comment by Denveous** [comment]
> The Song of Soaring/Song of Time animations have never been skippable to the best of my knowledge, except maybe in the 3DS version? I honestly never tried on the 3DS since I assumed you couldn't.

You are absolutely correct, no edition of the game has ever allowed that.

**Comment by danielryb** [comment]
> The Song of Soaring/Song of Time animations have never been skippable to the best of my knowledge, except maybe in the 3DS version? I honestly never tried on the 3DS since I assumed you couldn't.

Yes, it's entirely skippable on 3DS. Here's a [video](https://youtube.com/clip/UgkxmMs8J8lklI72ovecsDE2FYsS0cAT7PXa?si=fXYl0E_qMivcyIKN) featuring it.

**Comment by Mr-Wiseguy** [comment]
The next release will have this as #409 has been merged.
