### ISSUE TITLE
[Feature request] Adding compatibility with "Legend of Zelda, The: Ocarina of Time - Master Quest"

### ISSUE THREAD

**Issue by Elolawyn** [Mr-Wiseguy/Zelda64Recomp#405]
Since Ocarina of Time support is already one of the Planned Features, could I request adding "Legend of Zelda, The: Ocarina of Time - Master Quest" suport as well, eventually?

Given that it is an official version of the game and not just any random hack...

**Comment by Mr-Wiseguy** [comment]
I'm sure that master quest dungeons will be playable in some shape or form in the long run, but it won't be as easy as just recompiling the master quest ROM. Every ROM recompilation effectively produces a new executable, meaning every enhancement and patch would have to be ported from the vanilla OoT recompilation to the master quest one if I were to go that route. It would also mean that mods have to pick between being compatible with vanilla OoT or master quest. This is the same reason that I can't just recompile the PAL Majora's Mask ROM for other language support, for example.

Even if I don't get to adding built-in master quest functionality myself (which is pretty likely since I have a lot on my plate as it is), I'm sure somebody will make a mod that adds it. The modding framework will be very capable of a feature like importing the MQ maps. Closing this for that reason.
