### ISSUE TITLE
Missing Sample Positions Support on Linux (Mesa 24.1.1, AMD Radeon RX 7900 XTX)

### ISSUE THREAD

**Issue by RotDogWater** [Mr-Wiseguy/Zelda64Recomp#406]
**What is your GPU driver version?**
Mesa 24.1.1

**Describe the bug**
Z64 Recompiled reports that MS Anti-Aliasing is unavailable despite having a pretty new card and up to date driver.

**To Reproduce**
1. Go to Settings
2. Select Graphics

**Expected behavior**
Anti-Aliasing would be possible to be enabled, as this functions as expected in Windows 10/11 with the exact same hardware configuration.

**Screenshots**
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/85472232/70dfab91-69b7-4509-b037-ad189fd2f77f)

**Desktop (please complete the following information):**
 - OS: Bazzite (Fedora-based Linux distro)
 - Version: Version 40 Desktop Stable
 - CPU: 16 × AMD Ryzen 7 5800X 8-Core Processor
 - GPU: AMD Radeon RX 7900 XTX
 - GPU driver: AMD Mesa 24.1.1

**Comment by Mr-Wiseguy** [comment]
This isn't something recomp or RT64 can control, it's up to the driver. Mesa disabled sample position support on recent AMD hardware, apparently it causes Mesa to fail their Vulkan conformance test suite so they disabled it as a workaround for now. The AMD driver on Windows is a completely different one from Mesa, which is why you can use MSAA on Windows. Closing since there's nothing we can do about it, as sample positions is required to avoid artifacts when MSAA is enabled.

**Comment by Mr-Wiseguy** [comment]
Here's the line of Mesa's source code that contains that workaround: https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/amd/vulkan/radv_physical_device.c?ref_type=heads#L648
For reference, GFX10 and up would cover anything Navi 1 and newer, which is the RX 5000 series and up.

**Comment by i-can-not-program** [comment]
It appears to work using amdvlk
