### ISSUE TITLE
[Feature Request] Add FXAA as an anti-aliasing option

### ISSUE THREAD

**Issue by RotDogWater** [Mr-Wiseguy/Zelda64Recomp#407]
Due to limitations with the Mesa driver on Linux, (see [#406](https://github.com/Zelda64Recomp/Zelda64Recomp/issues/406)) it would be nice to have an option for a less robust anti-aliasing stopgap. This could also be useful for more modest hardware configurations, so that there is another option other than disabling AA entirely.

**Comment by DarioSamo** [comment]
I don't want FXAA. Just wait for Mesa to fix the issue.

**Comment by Mr-Wiseguy** [comment]
Since this would be a feature in the renderer, the decision is up to Darío. I do agree though that it's not worth adding FXAA (which produces visual artifacts, isn't designed for retro games, and arguably produces sub-par results) just to work around a driver-side issue, especially when the hardware is perfectly capable of MSAA.
