### ISSUE TITLE
Can't catch Magic Mushrooms

### ISSUE THREAD

**Issue by ravillarreal** [Mr-Wiseguy/Zelda64Recomp#416]
**Describe the bug**
I can't catch Magic Mushroom with Mask of Scents in purple areas (bathroom and guests rooms inside Clock Town)

**To Reproduce**
1.Go to Clock Town motel bathroom
2. Equip Mask of scents and Empty Bottle
3. When the smell appears, try to catch with bottle
4. nothing happens

**Expected behavior**
It should get the Magic Mushroom

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 22H2 build 19045.3693
 - CPU: AMD Ryzen 9 5900HX with Radeon Graphics 3.30 GHz
 - GPU: NVIDIA Geforce RTX 3060 mobile
 - GPU driver: Geforce Game Ready Driver 555.85

**Comment by Mr-Wiseguy** [comment]
Please upload your save file (and optionally record a video of you trying to do it), as nobody else has had this issue and I'd need to be able to reproduce it to verify and fix it.

**Comment by ravillarreal** [comment]
Nvm i managed to get it, but in the gorman's bed on the first day, i thought that i could get it in the toilet since it emits that purple smoke, but thanks for the quick response!

**Comment by Harpenen** [comment]
I'm encountering the same issue with the scent in the inn bathroom. Even though the scent in the bathroom can be Z targeted while wearing the Mask of Scents and Tatl will explain what you're supposed to do with it, it seems to be impossible to collect it with a bottle.
However, I still have this issue when attempting to collect it on two different emulators, so while this is probably a bug, it's likely not an issue with this port.
In Majora's Mask 3D, the Magic Mushroom can be collected as expected.

Since this seems to be an issue with the original game, I don't know if that's something this project would fix, but I can still share videos and save files if desired.
