### ISSUE TITLE
[Feature Request] Emulator style save states.

### ISSUE THREAD

**Issue by ripnetuk** [Mr-Wiseguy/Zelda64Recomp#418]
This game is hard. And I (like I would guess a number of us here) am old enough to have bought the N64 on launch, and am no longer as nimble as I was.

Took days to beat the archery challenge (lpt, use a mouse), and now I'm stuck on the beaver race.

Not sure how feasible it is on a recompile, but I would love to see emulator style save states. As in capture the exact moment in the game, and allow a rewind to that state, without having to find an owl statue or rely on auto save.

Bonus points for having multiple save slots.

**Comment by 111ebobo** [comment]
Well, this is out of scope, I think, and it could change the gameplay

**Comment by Reonu** [comment]
It's not necessarily out of scope. There's leftover code for this feature in the codebase, but it was never finished. If it was implemented it would be optional and off by default if I had to guess.

As to whether it's a priority, Wiseguy is the one who can answer that, but please don't claim whether something is out of scope without letting him give his thoughts first.

**Comment by ripnetuk** [comment]
> Well, this is out of scope, I think, and it could change the gameplay

It would indeed. Although to be fair, the switch version on NSO apparently supports this.

I think wiseguy has a vision of a plug in system for mods, which are out of scope of the goal of getting a cracking simple to use port of the game, so maybe it would fit in better here, assuming the plugin API is rich enough to allow this (it's pretty wide ranging in terms of what it woild need to touch).

**Comment by 111ebobo** [comment]
> > Well, this is out of scope, I think, and it could change the gameplay
> 
> It would indeed. Although to be fair, the switch version on NSO apparently supports this.
> 
> I think wiseguy has a vision of a plug in system for mods, which are out of scope of the goal of getting a cracking simple to use port of the game, so maybe it would fit in better here, assuming the plugin API is rich enough to allow this (it's pretty wide ranging in terms of what it woild need to touch).

Well, the NSO version is just the original version running on an emulator and here is a native port, and mods will, either change the whole gameplay like ROM hacks or simply change the models (but GS cheats could be added through that)

**Comment by Mr-Wiseguy** [comment]
While emulator-like save states could technically work in recomp and I have tested a prototype of them in the past, I realized there are enough limitations that they wouldn't be particularly useful. Namely:
1) Every update to recomp would break save states as the memory layout of the patch code would change whenever patches are changed.
2) Recomp will be getting mod support in the near future. Installing, updating, or removing mods would also break save states, for the same reason that updating recomp would break them.
3) My testing with save states was only done within a single play session. Making save states work across play sessions, even on the exact same recomp binary, may end up proving to be very difficult as memory addresses change every time a program starts on modern systems (a feature called ASLR, which exists for security reasons). It shouldn't be too bad to work around this by recreating the necessary state instead of simply copying it as-is, but since I haven't tried it yet I definitely wouldn't commit to anything.

If recomp ever got some sort of save states, it'd likely be in the debug menu only and with big disclaimers saying that stability isn't guaranteed.

**Comment by ripnetuk** [comment]
Thanks for the explanation Mrwiseguy. That all makes perfect sense that the layout of the storage will change between runs/builds.

Although to be honest, even if they only persisted within one play session that would be enough to allow people to replay challenging bits of the game without having to rewind time and find the place again, but arguably that is a massive change to gameplay.

Thanks again for this wonderful port. I'm having the time of my life playing through :)
