### ISSUE TITLE
Zora link crashes when using the hookshot

### ISSUE THREAD

**Issue by ActuallyTheOwner** [Mr-Wiseguy/Zelda64Recomp#421]
When Zora link uses the hookshot, the game crashes

**Expected behavior**
Zora link can be forced to use the hookshot via equip swap, or the zora item anywhere glitch.

**Unexpected behavior**
When Zora link uses the hookshot, the game crashes.

**Screenshots**
N/A

 - Debian 12.5
 - Version: 1.1.1
 - AMD 5600x
 - Nvidia 3060
 - Nvidia 535.183.01 proprietary drivers
 
**Additional context**
The game does not freeze, this is a hard crash

**Comment by ActuallyTheOwner** [comment]
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/26422734/517a1764-14ac-426a-89f9-e27dfa9a661b)
Forgot to mention, deku sticks work

**Comment by ActuallyTheOwner** [comment]
![image](https://github.com/Zelda64Recomp/Zelda64Recomp/assets/26422734/8905d018-16b9-4ea7-9927-c211944f6754)
The bow also works, but is rendered weird

**Comment by Mr-Wiseguy** [comment]
As has been the case with two of the other issues you've opened, this has the same behavior in the original game. There's a reason that the issue template asks "Have you checked whether this issue is vanilla behavior?" and "Were you playing with intended mechanics, or using glitches?", both of which you've removed from your issue report. As I said in your other issues, changing vanilla behavior that happens when deliberately using glitches is not in the scope of this base project. Doing so can have unintended side effects and is best left to mods when mod support is added. Please do not open any more issues issues like these.
