### ISSUE TITLE
cmake - No Sources given to target: RecompiledFuncs

### ISSUE THREAD

**Issue by Fondant** [Mr-Wiseguy/Zelda64Recomp#46]
**Describe the bug**
`
CMake Error at CMakeLists.txt:41 (add_library):
  No SOURCES given to target: RecompiledFuncs

CMake Generate step failed.  Build files cannot be regenerated correctly.
`
**To Reproduce**
try to build the project via cmake after building and adding rsp from n64recomp

**Desktop (please complete the following information):**
 - OS: Linux mint 
 - Version: 21.3
 - CPU: AMD Ryzen 7 2700X (16) @ 3.700G
 - GPU: NVIDIA GeForce RTX 3080 Ti

**Screenshots**
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/1091573/d4e9df85-f0d4-4f77-994b-71ea0ca4ef86)

**Additional context**
mostly just lost on how to produce this requirement for cmake at this point, seem to be pretty close to getting it to compile

**Comment by VikingSchism** [comment]
Got this myself - not really sure what to do from here
Looking in the rsp directory it looks like the only file in there is a gitignore with one of the entries being this missing file that is causing the error here
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/25965731/11472959-a735-45f6-9141-5a91a6fb87b2)

**Comment by PaulGrandperrin** [comment]
I guess that's where the output of recompiling the rom is used.
I compiled the N64Recomp tool but I don't know how to use it. It needs some kind of elf, but I have no idea what it really means.

**Comment by Fondant** [comment]
i was actually able to figure out how to produce the rspMain.cpp by unediting out the hard coded values for MM in the N64Recomp project and then providing the decomp file (which is what it means be decompressed apparently) and running it thru the rspRecompiler

**Comment by briaguya0** [comment]
I used a `.elf` produced by running `make init` on latest upstream decomp `expected/build/n64-us/mm-n64-us.elf`
```
md5sum mm-n64-us.elf 
650610fa16c8768864f977dd3fb5ab36  mm-n64-us.elf
```
because `make init` on the version of decomp in the submodule on this repo was failing for me with this error
```
RuntimeError: 'jr' instruction does not have an 'jump label' field
make[1]: *** [Makefile:320: disasm] Error 1
```
i then copied that `.elf` up to the top level `Zelda64Recomp` directory (where it is a sibiling of `us.rev1.toml` and renamed it `mm.us.rev1.elf`

i cloned and built `N64Recomp` (so the `N64Recomp` directory is a sibling of the `Zelda64Recomp` directory), then from the `build` directory in `N64Recomp` i ran
```
./N64Recomp ../../Zelda64Recomp/us.rev1.toml
```
which produced the following error
```
Sections
[WARN] LO16 reloc index 2144 in section ..ovl_En_Fishing referencing symbol 70139 with offset 0x80907834 follows LO16 with different symbol
[WARN] LO16 reloc index 63 in section ..ovl_En_Cne_01 referencing symbol 4614 with offset 0x809CBA44 follows LO16 with different symbol
[WARN] LO16 reloc index 92 in section ..ovl_Boss_07 referencing symbol 37735 with offset 0x809F5628 follows LO16 with different symbol
[WARN] LO16 reloc index 95 in section ..ovl_Boss_07 referencing symbol 52290 with offset 0x809F5634 follows LO16 with different symbol
Num symbols: 120102
Could not find entrypoint function
```
and no `RecompiledFuncs` directory was generated

this was on linux (debian sid)

**Comment by briaguya0** [comment]
@Fondant do you mean you uncommented [this](https://github.com/Mr-Wiseguy/N64Recomp/blob/dbf0e623c8a1cbb3e73237803a8bcc29f32816d6/RSPRecomp/src/rsp_recomp.cpp#L558-L566)?
```cpp
//// MM aspMain
//constexpr size_t rsp_text_offset = 0xC40FF0;
//constexpr size_t rsp_text_size = 0x1000;
//constexpr size_t rsp_text_address = 0x04001000;
//std::string rom_file_path = "../../MMRecomp/mm.us.rev1.z64"; // uncompressed rom!
//std::string output_file_path = "../../MMRecomp/rsp/aspMain.cpp";
//std::string output_function_name = "aspMain";
//const std::vector<uint32_t> extra_indirect_branch_targets{ 0x1F80, 0x1250, 0x1154, 0x1094, 0x1E0C, 0x1514, 0x1E7C, 0x1C90, 0x1180, 0x1808, 0x11E8, 0x1ADC, 0x1B6C, 0x1194, 0x1EF8, 0x1240, 0x17C0, 0x186C, 0x1A58, 0x18BC, 0x1ABC, 0x1ACC, 0x1A80, 0x1BD4 };
//const std::unordered_set<uint32_t> unsupported_instructions{};
```

**Comment by Fondant** [comment]
yes and commented out banjo-tooie

**Comment by briaguya0** [comment]
alright, i was able to generate `aspMain.cpp` and `njpgdspMain.cpp` by commenting out the `// BT n_aspMain` section, uncommenting the `// MM aspMain` and `// OoT njpgdspMain` sections (one at a time), building and running `RSPRecomp`

still not sure what's going on with the entrypoint when running `N64Recomp` though

**Comment by Melon-Bread** [comment]
Having similar issues, would help if the building section of the README had real instructions instead of saying "Just use the binary"

**Comment by raincode00** [comment]
I was able to get the RecompiledFuncs to generate after commenting out the `entrypoint = 0x80080000` and `"D_80186028"` lines in `us.rev1.toml`. 

The compilation eventually failed with this error: `RecompiledFuncs/__osRealloc.c:166:5: error: too few arguments to function ‘memmove’`  then eventually fails with `RecompiledFuncs/calloc.c:4:6: error: conflicting types for ‘calloc’; have ‘void(uint8_t *, recomp_context *)’ {aka ‘void(unsigned char *, recomp_context *)’}`.

**Comment by Fondant** [comment]
after looking at the decomp .elf for the entrypoint (it was offset by 60) and commenting out relocatable_sections_path and commented out the ignored thing like @raincode00 suggested, i got the cmake to finish. seems to be the same as raincode00's on build though

**Comment by briaguya0** [comment]
managed to get past the `calloc` and `memmove` issues by doing a find and replace in `RecompiledFuncs`

![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/70942617/85fe1eb2-c9eb-43df-a26f-01dd76dddd6b)

Started running into issues since I used the latest version of decomp instead of the submodule sha (renamed funcs etc.)

i'll probably try digging into getting that version of decomp to see if i can get past the
```
RuntimeError: 'jr' instruction does not have an 'jump label' field
make[1]: *** [Makefile:320: disasm] Error 1
```
error i was seeing before (which happened both when doing a local python venv and when using the docker instructions...)

**Comment by Fondant** [comment]
at this point i wonder if we have a version mismatch on the elf used and the one set up for this file...

**Comment by briaguya0** [comment]
it would be nice to know if this is expecting a non-matching elf, but i'm still pretty sure my current issues are stemming from the patches expecting an old version of decomp i can't get to build (and therefore generate all the asset headers/other decomp files it expects correctly)

**Comment by raincode00** [comment]
That jr instruction disasm error looks like it was fixed with this commit: https://github.com/zeldaret/mm/commit/3b8db093f6f9cfb5850a7100ba8aff0c1b099e42

Just replacing the line `insn.isJump():` with `insn.isJumpWithAddress():` in `tools/disasm/disasm.py` in the `getImmOverride` function was enough to get it going with the old version.

**Comment by briaguya0** [comment]
i tried cherry picking that commit and ran into a somewhat familiar error
```
[build] make: *** No rule to make target '../lib/mm-decomp/include/assets/text/message_data.h', needed by 'actor_transform_tagging.o'.  Stop.
```
looking at the diff between the submodule commit and that one https://github.com/zeldaret/mm/compare/5607eec18bae68e4cd38ef6d1fa69d7f1d84bfc8...3b8db093f6f9cfb5850a7100ba8aff0c1b099e42 something stood out https://github.com/zeldaret/mm/pull/1530

i'm going to try pulling https://github.com/zeldaret/mm/commit/3b8db093f6f9cfb5850a7100ba8aff0c1b099e42 directly instead of cherry picking to see what happens

**Comment by Fondant** [comment]
i started going about things a different way (may have tried to get that z64 to elf converter working) to see if just getting a ELF of MM would work without the decomp

**Comment by briaguya0** [comment]
same error there, tried replacing
```c
#include "assets/text/message_data.h"
```
with
```c
#include "../assets/text/message_data.h"
```

and got past that error, but then i was back to seeing a bunch of undefined identifiers in patches (`identifier "Gfx" is undefined` in `autosaving.c` for example)

dario told me
> yeah just give him some time, it's just a bit of a rough process he wants to streamline
> so hopefully along with the documentation it'll also be more automated

so i'm going to put this down for a while

**Comment by Fondant** [comment]
kk, im going to do a bit of hunting on this elf converter and do the same, i think

**Comment by briaguya0** [comment]
Amaro also mentioned they were able to generate `patches.elf` by adapting the patches to use the HM fork of mm decomp

https://github.com/Mr-Wiseguy/Zelda64Recomp/compare/dev...xoascf:Zelda64Recomp:dev-hm

**Comment by Zapeth** [comment]
I also spent some time trying to compile this project from scratch, but am now stuck at some unresolved references when linking the compiled files, which I'm not sure how to resolve.

More specifically, these from `Zelda64Recomp/src` files:
```
src/recomp/overlays.cpp: undefined reference to `load_patch_functions()'
src/recomp/recomp.cpp: undefined reference to `get_entrypoint_address()'
src/recomp/recomp.cpp: undefined reference to `recomp_entrypoint'
```
It seems `get_entrypoint_address` and `recomp_entrypoint` would be generated by `N64Recomp` if the .toml file is configured with an `entrypoint` address, but using the default value doesn't seem to work (as was already discussed above).

There are also a bunch of undefined references in `RecompiledFuncs` (some of these are also in `RecompiledPatches`), which I'm assuming should be extracted/generated by `N64Recomp`, but aren't for some reason (I'm using the generated .elf from the `zeldaret/mm` submodule):
```
undefined reference to `bzero_recomp'
undefined reference to `bcopy_recomp'
undefined reference to `bcmp_recomp'
undefined reference to `guScale'
undefined reference to `guMtxIdentF'
undefined reference to `guMtxF2L'
undefined reference to `guMtxIdent'
undefined reference to `guNormalize'
undefined reference to `guTranslate'
undefined reference to `ceilf_recomp'
undefined reference to `truncf_recomp'
undefined reference to `floorf_recomp'
undefined reference to `roundf_recomp'
undefined reference to `nearbyintf_recomp'
undefined reference to `nearbyint_recomp'
undefined reference to `__osGetFpcCsr'
```

**Comment by Alto1772** [comment]
I finally got how to resolve the undefined reference errors. Note that this only solves the building process above. There are some other caveats that I can't mention here...

Basically what I did is I selected the best possible commit revision from the decomp that matches the ones in the patches directory until I narrow it down that's best: https://github.com/zeldaret/mm/commit/0492c8e89af3806707e44a88379a3c8d9c503ca1

Then some tinkering with the disasm.py script that acknowledges N64Recomp to generate the necessary functions (**bzero, guScale, ceilf**): https://pastebin.com/N5s69HC5

This patch essentially contains:
- the jr disasm error fix: https://github.com/zeldaret/mm/commit/3b8db093f6f9cfb5850a7100ba8aff0c1b099e42
- some added assembler directives to set the correct symbol type and its size:
  - `.size <label>, . - <label>`
  - `.type <label>, @function` - this makes the entrypoint function visible.

To apply the patch make sure to checkout the commit hash mentioned above and be in a root directory.
```bash
git checkout 0492c8e89af3806707e44a88379a3c8d9c503ca1
curl -L https://pastebin.com/raw/N5s69HC5 | patch -p1
```

After building by `make init`, copy the ELF file and its uncompressed rom to the recomp and generate. Make sure `us.rev1.toml` is unmodified in order to make N64Recomp generate the expected results.
```bash
cp mm.us.rev1.rom_uncompressed.elf /path/to/Zelda64Recomp/
cd /path/to/Zelda64Recomp/
./N64Recomp us.rev1.toml
```

After successfully building it, testing the executable still has some problems, at least on my system:
```
$ ./build/Zelda64Recompiled                                
SVG plugin initialised.
Loaded font face 'rmlui-debugger-font' [regular] from 'memory'.
Loaded font face 'rmlui-debugger-font' [italic] from 'memory'.
Loaded font face 'LatoLatin' [regular] from 'assets/LatoLatin-Regular.ttf'.
Loaded font face 'Chiaro' [regular] from 'assets/ChiaroNormal.otf'.
Loaded font face 'Chiaro' [bold] from 'assets/ChiaroBold.otf'.
Loaded font face 'LatoLatin' [italic] from 'assets/LatoLatin-Italic.ttf'.
Loaded font face 'LatoLatin' [bold] from 'assets/LatoLatin-Bold.ttf'.
Loaded font face 'LatoLatin' [italic, bold] from 'assets/LatoLatin-BoldItalic.ttf'.
Loaded font face 'Noto Emoji' [regular] from 'assets/NotoEmoji-Regular.ttf'.
Loaded font face 'PromptFont' [regular] from 'assets/promptfont/promptfont.ttf'.
Failed to preload shader cache!
Failed to find function at 0x8017715C
[1]    135989 segmentation fault (core dumped)  ./build/Zelda64Recompiled
```

**Comment by raincode00** [comment]
I was also able to successfully build it on my end following @Alto1772's instructions. I was able to launch the executable, select a rom from the launcher, but I got a segfault immediately after clicking start game. The menus and settings in the launcher all appear functional though.

**Comment by Mr-Wiseguy** [comment]
Closing as build instructions have been added since this issue was opened.
