### ISSUE TITLE
[Question] How to use .nrm file after building MMRecompModTemplate

### ISSUE THREAD

**Issue by Captainkittyca2** [Mr-Wiseguy/Zelda64Recomp#485]
What to do with the generated nrm and dll files when building the mod template (how to use them in-game/where to place them in Zelda64Recomp folder)?

**Comment by Mr-Wiseguy** [comment]
You need to build the modding branch of this repo (https://github.com/Zelda64Recomp/Zelda64Recomp/tree/modding) and then place the nrm and dll in a folder called "mods" placed in the program's appdata folder (as in `%localappdata/Zelda64Recompiled/mods`). If you build a debug version of the branch, you should see prints in the console showing what mods were detected. If you have any trouble getting the branch to build, once I have a PR for the branch opened you'll be able to just download a build artifact instead of building it yourself.

**Comment by Captainkittyca2** [comment]
Thanks for the response! I'll check that branch out. Would building the modding branch of Zelda64Recomp be the exact same process as building the default branch? Also, would I only need to place these 2 files (highlighted files) in the "mods" folder, or would I have to place the rest too (the non-highlighted) 
![image](https://github.com/user-attachments/assets/5f126c74-79d6-4b3c-afbd-505d3c5ca918)

**Comment by Mr-Wiseguy** [comment]
The process is the same as building the main branch, just make sure you update your submodules recursively when switching branches. You only need to copy the dll and nrm files, but if you also copy the pdb and your mod crashes then Visual Studio will be able to show you what function it crashed in. In the future when the LuaJIT recompilation for mods is finished, you'll only need the nrm and won't even need to build a dll or run the offline mod recompiler.

**Comment by Captainkittyca2** [comment]
Thanks! I tested it out and it seems to work as intended. (Link auto-spin attacks when pressing B button, instead of charging the B button)
