### ISSUE TITLE
Program doesn't open in older Windows 10 updates

### ISSUE THREAD

**Issue by Tasosgemah** [Mr-Wiseguy/Zelda64Recomp#50]
Is this intended? I'm still using Windows 10 1909 as my main and i have to update it for this program to function it seems. But there might be reasons for someone not wanting to update Windows so i was wondering if there's no choice, thanks.

**Comment by Mr-Wiseguy** [comment]
Yes, that version of Windows is too old and in fact has been [end of life'd by Microsoft 3 years ago](https://learn.microsoft.com/en-us/lifecycle/announcements/windows-10-1909-end-of-servicing). Recomp and RT64 require moderately up-to-date installs of Windows in order to use recent graphics API features for optimal user experience and performance.
