### ISSUE TITLE
Lens of truth low FPS

### ISSUE THREAD

**Issue by SealEnthusiast** [Mr-Wiseguy/Zelda64Recomp#514]
**FIXED, TLDR if you play at high res, turn off MS-AA**

**Describe the bug**
When using the modding branch and running above the original FPS, The lens of truth causes fps slow-downs (I think its reverting to the original FPS)

**To Reproduce**
1. Go to Snowhead and obtain the lens of truth
2. Use the lens of truth

**Expected behavior**
FPS maintained

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Version: 24H2
 - CPU: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz   3.50 GHz
 - RAM: 64.0 GB (63.9 GB usable)
 - GPU: NVIDIA GeForce RTX 3060
 - GPU driver: Nvidia driver 566.03

https://github.com/user-attachments/assets/f879347f-ef1e-4702-88c4-d54d97cfe381

**Comment by SealEnthusiast** [comment]
Okay so this is a little weird, when using ANY TEXTURE PACK and having MS-AA enabled it will absolutly will destroy your FPS when the lens is equiped

Turning off MS-AA fixes the issue

I will keep the issue open as I am not sure if It is a problem with the texture packs or AA

**Comment by Mr-Wiseguy** [comment]
The issue isn't related to texture packs, you get a similar performance hit regardless of one being active (and it happens on the 1.1.1 release as well). The way lens currently works takes a big hit to framerate because it replicates the exact algorithm that the original implementation on N64 uses, which isn't an efficient way to produce the effect on a modern GPU. This was done for accuracy purposes to match the original game as closely as possible, but we want to replace it with a new algorithm that produces accurate visuals and performs much better in the future.

The performance hit happens no matter what settings you're on, it's just that normally the FPS is so high that it's still above your monitor's refresh rate. The combination of 4k + MSAA + lens on a 3060 happens to be enough to finally produce a visible framerate drop. If the lens of truth optimization ends up in 1.2 then this should go away.

**Comment by DarioSamo** [comment]
My personal recommendation would indeed to not use MSAA. Regardless of the game being very simple visually, using 4K resolution + MSAA has a fixed cost for each full-screen copy that the effect requires and it hits a bottleneck pretty quickly due to memory bandwidth limitations. As Wiseguy mentioned, the way it was implemented on the original game performs about three fullscreen copies on its own.

I do not think the visual quality improvement of MSAA is worth the hit on 4K even on stronger hardware like the 3090 Ti I use myself, so I think you'd be fine with turning it off.

**Comment by SealEnthusiast** [comment]
Thanks for the info both of yall, And thanks so much for your hard work on the Recomp and RT64.
