### ISSUE TITLE
[Question] Will the release version also include a spot/support for the OoT Spaceworld rom? 

### ISSUE THREAD

**Issue by Nicolas-Miranda** [Mr-Wiseguy/Zelda64Recomp#523]
As mentioned in the title, it would be nice if the final release includes a spot for the Oot Spaceworld 97 ROM along with the playable OoT for people to experience the early stages of OoT.

**Comment by Reonu** [comment]
The ROM you mention doesn't exist. If it existed it would be a leak that we can't use. And even if it both existed and we were able to use it, that's completely outside of the scope of this project. 

There are recreations of this ROM around, but they're all partially subjective recreations since inevitably they have to imagine what we don't have footage of, so even if we wanted to do this there would be no way to have the "definitive" Spaceworld experience. 

In any case mod support is coming and once it's released people will be able to distribute such projects as Recomp mods, which you will then be able to enjoy with all of the Recomp improvements.
