### ISSUE TITLE
Executable don't launch on Zorin OS 17.1 Core

### ISSUE THREAD

**Issue by kayoGc** [Mr-Wiseguy/Zelda64Recomp#64]
### Bug description 
i've been facing some problems while trying to launch the Zelda64Recompiled executable, after searching for solutions i could resolve some of them but now i reached in one that i have no ideia how to solve. The problems are the following:

1. When trying to run through the terminal the message `error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory` was displayed. The solution i used was to download the library: `apt-get install libsdl2-2.0-0`. (solution found [here](https://stackoverflow.com/questions/29711336/libsdl2-2-0-so-0-cannot-open-shared-object-file);

2. After that when trying to run again the terminal shows: `ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave`. The solution i used is from this [post](https://dev.to/setevoy/linux-alsa-lib-pcmdmixc1108sndpcmdmixopen-unable-to-open-slave-38on) of dev.to;

3. Now it shows the following error: `Segmentation Fault`  it also shows `ALSA lib pcm.c:8568:(snd_pcm_recover) underrun occurred` sometimes.

### To reproduce
1. launch the `Zelda64Recompiled` executable on Zorin OS 17.1 Core.

### Screenshots
![zeldaRecompiler-error](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/117952963/197eddca-18e5-43a8-a442-faf5e585eb11)

(Falta de segmentação = Segmentation Fault)

### Desktop
 - OS: Linux Distro - Zorin OS 
 - Version: 17.1 Core
 - CPU: AMD ryzen 7 2700u
 - GPU: AMD Randeon 500 series

**Comment by Ammako** [comment]
Spotty Linux compatibility is a known issue. Blame Linux in general for having 540 different distributions and software configurations, a build made one one distro may not work on other distros because they don't all have the same versions of libraries and such.

You can mess with trying to figure out how to build it on your own, or wait for build instructions in a little bit. A flatpack and/or appimage should be made eventually which should resolve inter-distro compatibility problems.

**Comment by kayoGc** [comment]
Oh i didn't see that it was a know issue, thanks for pointing that out! I'll try to figure how to build it.

**Comment by Ammako** [comment]
Yeah, it's way at the bottom of the readme. It should have been mentioned on the release honestly.
