### ISSUE TITLE
DirectX 11

### ISSUE THREAD

**Issue by FailerO** [Mr-Wiseguy/Zelda64Recomp#73]
Is it possible to add DirectX 11 support for older gpus in a future update?

**Comment by anthonywww** [comment]
Vulkan and OpenGL should be prioritized over anything closed-source/Windows exclusive.

**Comment by DarioSamo** [comment]
> Vulkan and OpenGL should be prioritized over anything closed-source/Windows exclusive.

A Vulkan backend is already implemented and currently used in Linux. D3D12 is the default on Windows because it usually has a better shot at being supported correctly.

I'm not sure how feasible a DX11/GL Backend is considering the architecture and design of the features RT64 relies on. The renderer is designed around modern APIs and the RHI is a very thin abstraction layer for those.

**Comment by Reonu** [comment]
API Support is currently mandated by what APIs are supported by RT64, so discussions about older API support should happen over at https://github.com/rt64/rt64
