### ISSUE TITLE
[Feature request] Add option for loading roms with custom CRC

### ISSUE THREAD

**Issue by ZethRyder** [Mr-Wiseguy/Zelda64Recomp#83]
While it's possible to run the vanilla game on the recomp, however it does not recognize correctly any Majora's Mask Roms that has had the CRC changed. Any Zelda 64 hacks that were made prior to decomp required the CRC to be fixed otherwise the rom would not boot.  Would love to be able to run some of the custom hacks using this since they are running on the NTSC roms whether its CRC related or MD5 that prevents the roms from being used.

**Comment by g-l-i-t-c-h-o-r-s-e** [comment]
I second this motion

**Comment by Mr-Wiseguy** [comment]
Recomp is not an emulator, so it can't just run arbitrary ROMs even if you were to bypass the hash check (which is unrelated to the CRC that you need to change for the ROM to boot in console/emulator). Most modified ROMs, even asset ones, change the game's code in some way, which means they'd break in recomp since it runs the original game's code instead of the code in the ROM. There will be a way to convert patched ROMs into recomp mods in the future after recomp mod support is added, but this won't be a process end users would be dealing with since it'd be mostly focused at romhack authors.
