### ISSUE TITLE
Lack of GC controller support

### ISSUE THREAD

**Issue by fihn14** [Mr-Wiseguy/Zelda64Recomp#84]
GC adapter no workie!!! Using Official adapter with Zadig driver replacement on windows 11 pro

**Comment by briaguya0** [comment]
Native GC controller adapter support on windows isn't supported in SDL2, it will be supported in SDL3. In the meantime https://github.com/Struggleton/Delfinovin should work for you.

**Comment by Mr-Wiseguy** [comment]
Closing due to lack of response after a suggestion was given. Also, I'm not sure why you'd replace the driver with Zadig as that makes it impossible for programs expecting the normal driver to recognize the device. I've heard other people had success with the official adapter, so I have a strong feeling that the driver replacement is the issue here. Feel free to reopen if the suggestion doesn't work for you and if resetting to the original driver doesn't fix it either.

**Comment by briaguya0** [comment]
adding context in case someone else stumbles upon this issue in the future

> I'm not sure why you'd replace the driver with Zadig as that makes it impossible for programs expecting the normal driver to recognize the device.

there is no "normal" driver for the official switch/wii u gc controller adapters. the zadig method is a very commonly recommended way to use those adapters on windows.

the [dolphin wiki recommends](https://wiki.dolphin-emu.org/index.php?title=How_to_use_the_Official_GameCube_Controller_Adapter_for_Wii_U_in_Dolphin) using the zadig driver replacement to use the built in native gamecube controller support

the [delfinovin setup guide](https://github.com/Struggleton/delfinovin-docs/wiki/Setup-Guide) recommends using the zadig driver replacement as well. delfinovin interacts with that and creates virtual xinput devices that are recognized by pretty much all modern games

there are also third party adapters that can be toggled between pc and switch/wii u modes - the pc mode drivers for those are hit or miss at best, and delfinovin is generally recommended over using those adapters in pc mode
