### ISSUE TITLE
Not launching on ARM 

### ISSUE THREAD

**Issue by GuythatUhmCreatesRandomStuff** [Mr-Wiseguy/Zelda64Recomp#94]
**Describe the bug**

Basically it tries to find the ALSA audio driver but it cant find the audio device since its just a proot container

**To Reproduce**

Get on a proot container with raspbian proot
Run executable with box64
See error

**Expected behavior**

Just launching the game with no audio.

**Screenshots**
Please attach a screenshot of the bug.

![Screenshot_20240512-125848_TermuxX11](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/144390627/adfbefca-b05c-4c05-a11a-f36b9fa04cbd)

**Desktop (please complete the following information):**
 - OS:[Raspbian]
 - Version: [1.0.0]
 - CPU: [Exynos 850.]
 - GPU:[Mali G52, software rendering]

**Additional context**

running android 12 with termux and LXDE as desktop, can use zink for more openGL functionality

**Comment by Mr-Wiseguy** [comment]
This is a doubly unsupported setup, firstly because you're emulating the x86 version on ARM and secondly because there are no Vulkan drivers for the Mali G52 under Linux. I don't think there's much value in debugging a software renderer, since the performance (especially on a mobile chipset like this) would almost certainly be unusably slow.
