### ISSUE TITLE
[Feature Request] Multilanguage / EU support

### ISSUE THREAD

**Issue by JJihiro** [Mr-Wiseguy/Zelda64Recomp#97]
Will Europe version be supported at some point ?
Or is there a way to use another language ?

**Comment by Reonu** [comment]
Thank you for your issue!

Multilanguage support is planned, but we don't have specifics to share on the implementation just yet.

**Comment by Reonu** [comment]
Reopening this issue since it's a valid feature request and something that is planned but not implemented yet

**Comment by TedMosly** [comment]
Hope there will be also the support for Italian patch localization ( since the game was not published in Italy ) made by [Rulesless](https://drive.google.com/file/d/1tQf5gnX10PIiJq3_mG1dUWmt7XSMrUCp/edit)

**Comment by Reonu** [comment]
To clarify, when multi-language support is added, it will not require using a European ROM. Multi-language support will be added to the project itself, and it will be possible to load custom translations, so it will not be limited to the vanilla European translations.

**Comment by TedMosly** [comment]
> To clarify, when multi-language support is added, it will not require using a European ROM. Multi-language support will be added to the project itself, and it will be possible to load custom translations, so it will not be limited to the vanilla European translations.

wdym? for example for italian translations, I need to upload only the patch file "Legend of Zelda, The - Majora's Mask (ITA by Rulesless 2.3).**bps**" ? and the game will be in italian?

**Comment by SvenBudak** [comment]
To be honest, I usually use ChatGPT to translate my English posts. My English is passable, but not good enough to enjoy a story-driven game. I can hardly wait for EU (DE) support! :)

**Comment by colltyp** [comment]
> To clarify, when multi-language support is added, it will not require using a European ROM. Multi-language support will be added to the project itself, and it will be possible to load custom translations, so it will not be limited to the vanilla European translations.

But wouldn't it make more sense to use the vanilla translations because they would be of better quality than if you did it yourself and above all you have less work?

**Comment by Reonu** [comment]
> > To clarify, when multi-language support is added, it will not require using a European ROM. Multi-language support will be added to the project itself, and it will be possible to load custom translations, so it will not be limited to the vanilla European translations.
> 
> But wouldn't it make more sense to use the vanilla translations because they would be of better quality than if you did it yourself and above all you have less work?

I understand why you would think that, but I'm a licensed translator. I'm fairly certain that if I were to translate Majora's Mask to Spanish on my own it wouldn't be any lower quality of a translation than the vanilla one. This is why I will be in charge of the Spain Spanish translation.

But I'm **not** going to re-translate the entire game, the plan is to use the existing Spanish translation as a base and fix the errors it has.

For example, when you cross the first door after becoming a Deku in the intro, Tatl says the following in English: "That stuff back there...", referring to the events that just transpired, and then she apologises. In Spanish this sentence is translated as "Todo eso aquí de nuevo..." which means "All of that here again..." which makes no sense. Or at the inn, when you go to your room and check the broken wall, Tatl says "For crying out loud, you can even hear the person on the other side". In Spanish this was translated to literally say that there is somebody crying on the other side. The translation isn't unsalvageable though, just needs some love.

Furthermore, what you are asking for would in fact be way more complicated. In order to support the European ROM and use the vanilla multi-language support like you're asking us to, we would have to port all the enhancements and changes that we've applied to the US version over to the EU version.

It is therefore easier to add multi-language support to the project itself, which has the added benefit that custom translations can be shared and loaded.

**Comment by SvenBudak** [comment]
> > > To clarify, when multi-language support is added, it will not require using a European ROM. Multi-language support will be added to the project itself, and it will be possible to load custom translations, so it will not be limited to the vanilla European translations.
> > 
> > 
> > But wouldn't it make more sense to use the vanilla translations because they would be of better quality than if you did it yourself and above all you have less work?
> 
> I understand why you would think that, but I'm a licensed translator. I'm fairly certain that if I were to translate Majora's Mask to Spanish on my own it wouldn't be any lower quality of a translation than the vanilla one. This is why I will be in charge of the Spain Spanish translation.
> 
> But I'm **not** going to re-translate the entire game, the plan is to use the existing Spanish translation as a base and fix the errors it has.
> 
> For example, when you cross the first door after becoming a Deku in the intro, Tatl says the following in English: "That stuff back there...", referring to the events that just transpired, and then she apologises. In Spanish this sentence is translated as "Todo eso aquí de nuevo..." which means "All of that here again..." which makes no sense. Or at the inn, when you go to your room and check the broken wall, Tatl says "For crying out loud, you can even hear the person on the other side". In Spanish this was translated to literally say that there is somebody crying on the other side. The translation isn't unsalvageable though, just needs some love.
> 
> Furthermore, what you are asking for would in fact be way more complicated. In order to support the European ROM and use the vanilla multi-language support like you're asking us to, we would have to port all the enhancements and changes that we've applied to the US ROM over to the EU ROM.
> 
> It is therefore easier to add multi-language support to the project itself, which has the added benefit that custom translations can be shared and loaded.

I am an app developer myself and I know a bit about writing reusable code... Therefore, I am wondering: If I understood correctly, N64Recomp Majora's Mask is just a kind of "playground" and the actual goal is to get N64Recomp to the point where you can recompile all the games that exist, right? You can't expect someone to translate all the games that exist... so why not just use the original text from the game? Doesn't that make more sense?

**Comment by colltyp** [comment]
> > > To clarify, when multi-language support is added, it will not require using a European ROM. Multi-language support will be added to the project itself, and it will be possible to load custom translations, so it will not be limited to the vanilla European translations.
> > 
> > 
> > But wouldn't it make more sense to use the vanilla translations because they would be of better quality than if you did it yourself and above all you have less work?
> 
> I understand why you would think that, but I'm a licensed translator. I'm fairly certain that if I were to translate Majora's Mask to Spanish on my own it wouldn't be any lower quality of a translation than the vanilla one. This is why I will be in charge of the Spain Spanish translation.
> 
> But I'm **not** going to re-translate the entire game, the plan is to use the existing Spanish translation as a base and fix the errors it has.
> 
> For example, when you cross the first door after becoming a Deku in the intro, Tatl says the following in English: "That stuff back there...", referring to the events that just transpired, and then she apologises. In Spanish this sentence is translated as "Todo eso aquí de nuevo..." which means "All of that here again..." which makes no sense. Or at the inn, when you go to your room and check the broken wall, Tatl says "For crying out loud, you can even hear the person on the other side". In Spanish this was translated to literally say that there is somebody crying on the other side. The translation isn't unsalvageable though, just needs some love.
> 
> Furthermore, what you are asking for would in fact be way more complicated. In order to support the European ROM and use the vanilla multi-language support like you're asking us to, we would have to port all the enhancements and changes that we've applied to the US version over to the EU version.
> 
> It is therefore easier to add multi-language support to the project itself, which has the added benefit that custom translations can be shared and loaded.

Makes sense of course if you take the original translation as a basis and correct the mistakes I mean the most famous example that is relevant to the lore is failed translation in English and German (maybe more languages) of the text what Demise says at the end in Skyward Sword in English it says "An incarnation of my hatred shall ever follow your kind, dooming them to wander a blood-soaked sea of darkness for all time! " while in Japanese he says something completely different, namely "My hatred the curse of the demon tribe they shall continously go on reincarnating until the end of all times" if the English only speaks of an incarnation, the Japanese speaks of a Demon Tribe which is something completely different but on the subject of doing the translation yourself, this is a very good idea to take the basis and improve the mistakes only I have made the experience that most fan translations for the German language are, for example, stronger than the English one. translations for the German language, for example, need a lot of improvement because they are only partially good and sometimes even very bad so I'm curious how good the German translation will be maybe I can even help but probably not at least currently

**Comment by adam-ikari** [comment]
I’m curious how you plan to achieve multi-language support? I’d like to add it to this project myself!

**Comment by rjceledon** [comment]
It would definitely make more sense to just allow the compatibility for PAL roms rather than translating the game on your own, this would add compatibility for ALL games, not just Zelda

**Comment by Mr-Wiseguy** [comment]
It doesn't make more sense to do it that way. "Adding compatibility" for running another ROM means recompiling it like how the US ROM has been recompiled. This produces an entirely different executable with different code, different memory layouts, and so on. Every patch that's been written for this project would have to be ported manually to the other ROM (which would be weeks of effort), and no mods written for one version would work on the other versions.

Doing it this way would also only give you the 3 other languages that the PAL version supports (2 in the case of Ocarina of Time since the N64 version doesn't include Spanish), meaning that effort would be pointless when it comes time to support other languages. There's also a lot of complications when it comes to rendering text that isn't using the Latin alphabet, such as languages that are read from right to left or languages with complex shaping and ligatures.

There's also the fact that PAL ROMs run at 50Hz, with no corrections to the gameplay speed to account for that. This means that the gameplay would be slower when using those 3 languages, unless somebody put in the time and effort needed to patch the game to run at 60Hz correctly.

It makes much more sense to build a framework for adding new translations to the game and using that to port the official translations with fixes like Reonu already explained. Doing it that way means you gain the ability to add tons of new languages, not just the 3 that the original game came with. You'd also be able to reuse a lot of this framework for other recompilations by making game-specific tweaks to how the text should be rendered and using different fonts, which means games that never even had other language support could potentially get it.

**Comment by rjceledon** [comment]
I thought the idea was to make an universal recompiler for all N64 games, as only allowing NTSC games will leave some "PAL-only" games out of sight, specially those japanese weird ones and some demos. I guess the team will end up working on the PAL recompilation either way at some point when the rest of work is finished. I don't think the N64 game developers back in the 90s had to completely re-do their games when building the NTSC/PAL version, guessing their original compiler would do it automatically or tweaking some code for it, I have no idea honestly, not a game developer myself. Any option would be great, just thinking that finding a way to recompile PAL games and convert them to NTSC, if needed, would be really valuable (although we all know it includes a lot of effort).

**Comment by Mr-Wiseguy** [comment]
> I thought the idea was to make an universal recompiler for all N64 games, as only allowing NTSC games

There's nothing stopping PAL only games from getting recompiled, that's not at all what I said. You can already run a PAL or JP ROM through the recompiler. What I said is that it's not a good solution to recompile the PAL version of this particular game alongside the NTSC version as a way to get multi-language support.

> I don't think the N64 game developers back in the 90s had to completely re-do their games when building the NTSC/PAL version

That's not what matters for a recompilation, all that matters is the contents of the ROM. Even just changing one line in the source code causes it to compile into a completely different ROM, as memory addresses shift around from things getting added or removed, meaning functions and variables are in completely different places. That's why you'd have to port all the patches to the other versions if you made a recompilation of the PAL ROM. It's a completely different ROM than the NTSC version, there's no way to just "convert" the PAL ROM's multi-language code into the NTSC ROM automatically.

If it was as easy as just running the PAL ROM through the recompiler to get multilanguage support in this project, I can promise you I'd have done it already.

**Comment by colltyp** [comment]
How many languages are planned for the games?

**Comment by SvenBudak** [comment]
> How many languages are planned for the games?

This question is inappropriate. No one can give you an answer to it because it is still too early to talk about such details. A strategy must first be developed on how exactly a translation system can be implemented. It makes perfect sense to use NTSC versions as a basis. Once the strategy is clarified, it must then be implemented. Only then will people from the community tackle the translations. There will be no "consortium" deciding which translations will come.

**Comment by Mr-Wiseguy** [comment]
@SvenBudak I don't know what you're talking about, it's a perfectly appropriate question to ask and it's not too early to talk about the details.

@colltyp The plan for built in languages will be the official translations we can reuse (with changes made to the Spanish one to fix some glaring mistranslations). That would mean Spanish, German, and French. From there, I plan on allowing this project to load custom translations so that community members can make and share their own ones, so there will be as many translations as people decide to make (though I can't make any guarantee of the quality of third party translations of course).

**Comment by Mr-Wiseguy** [comment]
Since the plans have been explained at this point and this discussion in this issue is getting a little off-topic, I'm going to promote it from an issue to a feature on the upcoming features list in the readme.

**Comment by JustJeff88** [comment]
I didn't see the readme or this discussion until Wiseguy commented. I'm glad that multi-language support is on the list of things to do. I'm a North American French speaker, and while many modern games are in French, games in French from early consoles were only for Europeans; this was often true for German, Spanish and Italian as well. Even if one imported the PAL version of Ocarina of Time or Majora's Mask from Europe, it wouldn't work in an NTSC console. It wasn't until the 3DS era that non-English translations for NA/NTSC games became common.

My appreciation to Wiseguy for his hard work.

**Comment by Raflos10** [comment]
Looking forward to this feature

**Comment by SunnyDylan** [comment]
wouldn't it be easier to add Japanese first? I'm talking from what benefits me, yes, but it wouldn't need a retranslation, so wouldn't it be faster? I'm looking forward to play it in the original language
